### ISSUE TITLE
Team 111 - Sunbeams HTML-and-CSS-Capstone-Project issues

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [tGodson/HTML-and-CSS-Capstone-Project#2]
Positive aspects of the project :         
-  Well, structured pages throughout the project.
-  The Dropdown Menu in the mobile view looks great and the presenter worked hard to make it work despite the challenge.
-   The presenter worked hard to make the project resemble the requirements specified.

Recommendations :  
-  JQuery link in the head element must be the first link above the other links, this will help with the menu dropdown in the mobile view.

**Comment by tGodson** [comment]
done
